name: near-runner
on: push
jobs:
  sandbox:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [14, 16]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: cd examples && yarn install && yarn test
